# This file overrides variables used by the makefile, so it's behaviour
# becomes suitable for building Debian packages.

PREFIX     = $(DESTDIR)/usr
CONFDIR    = $(DESTDIR)/etc/munin
HTMLDIR    = $(DESTDIR)/var/www/munin
DBDIR      = $(DESTDIR)/var/lib/munin
MANDIR     = $(PREFIX)/share/man

CGIDIR     = $(DESTDIR)/usr/lib/cgi-bin

LIBDIR     = $(PREFIX)/share/munin
JAVALIBDIR = $(DESTDIR)/usr/share/munin

HOSTNAME   = localhost.localdomain

PERLLIB    = $(DESTDIR)$(shell $(PERL) -V:vendorlib | cut -d= -f2 | sed "s/[\';]//g")

JC         = /usr/lib/jvm/java-6-openjdk/bin/javac
CHECKUSER  = \#
CHECKGROUP = \#
CHOWN      = \#
CHMOD      = \#
CHGRP      = \#
